# Generated by Django 3.2.2 on 2023-05-22 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=500)),
                ('fecha_fin', models.DateField()),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('estados', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Validado', 'Validado'), ('Cotizado', 'Cotizado'), ('Cancelado', 'Cancelado'), ('Terminado', 'Terminado')], default='Pendiente', max_length=100)),
                ('cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Detalles_proyecto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_visita', models.DateField()),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('descripcion', models.TextField(max_length=500)),
                ('empleados_id', models.ManyToManyField(blank=True, related_name='empleados', to='empleados.Empleado')),
                ('proyecto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyecto', to='proyectos.proyecto')),
            ],
        ),
    ]
