# Generated by Django 3.2.2 on 2023-05-06 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0004_empleado_tipos_empleado'),
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='descripcion',
            field=models.TextField(max_length=500),
        ),
        migrations.CreateModel(
            name='Detalles_proyecto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_visita', models.DateField()),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('descripcion', models.TextField(max_length=500)),
                ('empleados_id', models.ManyToManyField(blank=True, related_name='empleados', to='empleados.Empleado')),
                ('proyecto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyecto', to='proyectos.proyecto')),
            ],
        ),
    ]
