# Generated by Django 3.2.2 on 2023-05-21 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_auto_20230506_1542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyecto',
            old_name='accepted',
            new_name='estados',
        ),
    ]
