# Generated by Django 3.2.2 on 2023-04-26 00:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import empleados.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(999999999999), django.core.validators.MinValueValidator(100000)])),
                ('primer_nombre', models.CharField(max_length=100)),
                ('segundo_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('primer_apellido', models.CharField(max_length=100)),
                ('segundo_apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('edad', models.PositiveIntegerField(blank=True, null=True)),
                ('celular', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(3999999999), django.core.validators.MinValueValidator(3000000000)])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('foto', models.ImageField(default='users/user_default_profile.png', upload_to=empleados.models.user_directory_path_empleado)),
            ],
        ),
        migrations.CreateModel(
            name='Asignacion_Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleados', to='empleados.empleado')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyecto', to='proyecto.proyecto')),
            ],
        ),
    ]
