# Generated by Django 3.2.2 on 2023-05-06 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tipos_empleados',
            new_name='Tipos_empleado',
        ),
    ]
