# Generated by Django 3.2.2 on 2023-05-22 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_alter_empleado_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='celular',
            new_name='telefono',
        ),
    ]
