# Generated by Django 3.2.2 on 2023-05-06 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0003_empleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='tipos_empleado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tipo_empleado', to='empleados.tipos_empleado'),
            preserve_default=False,
        ),
    ]
