# Generated by Django 3.2.2 on 2023-05-22 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('empleados', '0004_rename_telefono_empleado_celular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='usuario_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleado_usuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
