# Generated by Django 3.2.2 on 2023-05-06 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='identificacion',
            new_name='cedula',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='date_created',
            new_name='fecha_registro',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='edad',
        ),
        migrations.AddField(
            model_name='profile',
            name='primer_apellido',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='primer_nombre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='segundo_apellido',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='segundo_nombre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
