# Generated by Django 3.2.2 on 2023-05-06 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20230506_1621'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Cliente',
        ),
    ]
