# Generated by Django 3.2.2 on 2023-05-22 18:44

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20230522_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='ciudad',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='departamento', chained_model_field='departamento', on_delete=django.db.models.deletion.CASCADE, to='usuarios.ciudad'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='departamento',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='pais', chained_model_field='pais', on_delete=django.db.models.deletion.CASCADE, to='usuarios.departamento'),
        ),
    ]
