# Generated by Django 3.2.2 on 2023-05-06 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_auto_20230506_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='pais_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pais_id', to='usuarios.pais'),
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('pais_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pais_id_departamento', to='usuarios.pais')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('departamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pais_id_departamento', to='usuarios.departamento')),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
            },
        ),
    ]
