# Generated by Django 3.2.2 on 2023-05-21 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_auto_20230506_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamento',
            name='pais_id',
        ),
        migrations.AddField(
            model_name='departamento',
            name='pais_id',
            field=models.ManyToManyField(related_name='pais_id_departamento', to='usuarios.Pais'),
        ),
    ]
