# Generated by Django 3.2.2 on 2023-05-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_auto_20230521_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ciudad',
            name='departamento',
        ),
        migrations.AddField(
            model_name='ciudad',
            name='departamento',
            field=models.ManyToManyField(related_name='departamento_id_ciudad', to='usuarios.Departamento'),
        ),
    ]
