# Generated by Django 3.2.2 on 2023-05-21 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_auto_20230521_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ciudad',
            name='departamento',
        ),
        migrations.AddField(
            model_name='ciudad',
            name='departamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='departamento_id_ciudad', to='usuarios.departamento'),
        ),
        migrations.AlterField(
            model_name='ciudad',
            name='nombre',
            field=models.CharField(blank=True, default='Medellin', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='nombre',
            field=models.CharField(blank=True, default='Antioquia', max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name='departamento',
            name='pais_id',
        ),
        migrations.AddField(
            model_name='departamento',
            name='pais_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pais_id_departamento', to='usuarios.pais'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='pais_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pais_id', to='usuarios.pais'),
        ),
    ]
