# Generated by Django 3.2.2 on 2023-05-21 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_auto_20230521_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudad',
            name='departamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='departamentos_id_ciudad', to='usuarios.departamento'),
        ),
    ]
