# Generated by Django 3.2.2 on 2023-05-21 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_alter_ciudad_departamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direccion',
            name='pais_id',
        ),
        migrations.AddField(
            model_name='direccion',
            name='pais',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuarios.pais'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='cliente_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuarios.cliente'),
        ),
    ]
