# Generated by Django 3.2.2 on 2023-05-21 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0014_auto_20230521_1239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departamento',
            old_name='pais_id',
            new_name='pais',
        ),
    ]
