# Generated by Django 3.2.2 on 2023-05-21 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0015_rename_pais_id_departamento_pais'),
    ]

    operations = [
        migrations.RenameField(
            model_name='direccion',
            old_name='cliente_id',
            new_name='cliente',
        ),
    ]
