# Generated by Django 3.2.2 on 2023-05-22 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materiales', '0001_initial'),
        ('proyectos', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subtotal', models.IntegerField(default=0)),
                ('descuento', models.IntegerField(default=0)),
                ('totol_pagar', models.IntegerField(default=0)),
                ('fecha_actualizacion', models.DateField()),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('proyecto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyecto_cotizacion', to='proyectos.proyecto')),
            ],
            options={
                'verbose_name': 'Cotizacion',
                'verbose_name_plural': 'Cotizaciones',
            },
        ),
        migrations.CreateModel(
            name='Detalle_cotizacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=0)),
                ('valor_total', models.IntegerField(default=0)),
                ('cotizacion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyecto', to='cotizacion.cotizacion')),
                ('materiales_id', models.ManyToManyField(blank=True, related_name='materiales_cotizacion', to='materiales.Material')),
            ],
            options={
                'verbose_name': 'Detalle_cotizacion',
                'verbose_name_plural': 'Detalle_cotizaciones',
            },
        ),
    ]
