# Generated by Django 3.2.2 on 2023-05-06 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyectos', '0002_auto_20230506_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subtotal', models.IntegerField(default=0)),
                ('descuento', models.IntegerField(default=0)),
                ('totol_pagar', models.IntegerField(default=0)),
                ('fecha_actualizacion', models.DateField()),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('proyecto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyecto_cotizacion', to='proyectos.proyecto')),
            ],
            options={
                'verbose_name': 'Cotizacion',
                'verbose_name_plural': 'Cotizaciones',
            },
        ),
    ]
