# Generated by Django 3.2.2 on 2023-05-06 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0002_alter_material_fecha_actualizacion'),
        ('cotizacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detalle_cotizacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=0)),
                ('valor_total', models.IntegerField(default=0)),
                ('cotizacion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyecto', to='cotizacion.cotizacion')),
                ('materiales_id', models.ManyToManyField(blank=True, related_name='materiales_cotizacion', to='materiales.Material')),
            ],
            options={
                'verbose_name': 'Detalle_cotizacion',
                'verbose_name_plural': 'Detalle_cotizaciones',
            },
        ),
    ]
